
# Example file for setting up exercises.

# The app name appears at the top of your exercise set.
app_name : 'phpTutor'

# Each exercise should be documented here.
exercises :
  # The key is the unique machine name.
  1 :
    # Human readable name.
    name : 'Exercise 1'
    # File to load.
    file : 'index.php'
  2 :
    name : 'Exercise 2'
    file : 'index.php'